# Generated by Django 3.0.7 on 2020-07-02 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0002_auto_20200630_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecreate',
            name='course_title',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='SyllabusAddition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=50)),
                ('link', models.CharField(choices=[('IT/Software', 'IT/software'), ('Engineering', 'engineering'), ('UPSE', 'upse'), ('SSC', 'ssc')], max_length=15)),
                ('title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courseapp.CourseCreate')),
            ],
        ),
    ]
