# Generated by Django 3.0.7 on 2020-07-02 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0003_auto_20200702_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syllabusaddition',
            name='link',
            field=models.CharField(max_length=250),
        ),
    ]
